name: my_new_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  flutter_svg: ^2.0.10
  flutter_screenutil: ^5.9.0
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - assets/images/
    - lib/assets/images/man.png
    - lib/assets/images/wowan.png
    - lib/assets/images/shirt.png
    - lib/assets/images/Transfer Document icon.png